/**
 * Format stage — emits schemas, diagrams, and placement maps to .ada/format/.
 *
 * Implemented within the compiler package to avoid a circular dependency:
 *   @ada/config-writer → @ada/compiler (types)
 *   @ada/compiler      → @ada/config-writer (would be circular)
 *
 * The logic mirrors the emitters in packages/config-writer/src/emitters/ but
 * operates on types already available here.
 */

import * as fs from "fs";
import * as path from "path";
import type { Blueprint, EntityMap, Entity, BoundedContext } from "./types.js";

// ─── Helpers ────────────────────────────────────────────────────────────────

function toPathSegment(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function mermaidId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function mapToTSType(rawType: string): string {
  const t = rawType.toLowerCase().trim();
  if (t === "number" || t === "int" || t === "integer" || t === "float") {
    return "number";
  }
  if (t === "boolean" || t === "bool") return "boolean";
  if (t === "date" || t === "datetime" || t === "timestamp") return "Date";
  return "string";
}

function mapToZodPrimitive(rawType: string): string {
  const t = rawType.toLowerCase().trim();
  if (t === "number" || t === "int" || t === "integer" || t === "float") {
    return "z.number()";
  }
  if (t === "boolean" || t === "bool") return "z.boolean()";
  if (t === "date" || t === "datetime" || t === "timestamp") return "z.date()";
  return "z.string()";
}

function invariantToRefine(predicate: string): string | null {
  const p = predicate.toLowerCase();

  const nonEmptyMatch = /(\w+)\s+must\s+be\s+non-?empty/.exec(p);
  if (nonEmptyMatch) {
    const field = nonEmptyMatch[1] ?? "value";
    return `.refine(data => (data.${field}?.length ?? 0) > 0, { message: "${predicate}" })`;
  }

  const positiveMatch = /(\w+)\s+must\s+be\s+positive/.exec(p);
  if (positiveMatch) {
    const field = positiveMatch[1] ?? "value";
    return `.refine(data => (data.${field} ?? 0) > 0, { message: "${predicate}" })`;
  }

  const greaterMatch = /(\w+)\s+must\s+be\s+greater\s+than\s+(\d+)/.exec(p);
  if (greaterMatch) {
    const field = greaterMatch[1] ?? "value";
    const threshold = greaterMatch[2] ?? "0";
    return `.refine(data => (data.${field} ?? 0) > ${threshold}, { message: "${predicate}" })`;
  }

  return null;
}

// ─── Schema emitter ──────────────────────────────────────────────────────────

function emitEntitySchema(entity: Entity): string {
  const propLines = entity.properties.map((p) => {
    const tsType = mapToTSType(p.type);
    const optMark = p.required ? "" : "?";
    return `  readonly ${p.name}${optMark}: ${tsType};`;
  });

  const interfaceDeclaration = [
    `export interface ${entity.name} {`,
    ...propLines,
    `}`,
  ].join("\n");

  const zodFields = entity.properties.map((p) => {
    const base = mapToZodPrimitive(p.type);
    const optionalSuffix = p.required ? "" : ".optional()";
    return `  ${p.name}: ${base}${optionalSuffix},`;
  });

  const refines = entity.invariants
    .map((inv) => invariantToRefine(inv.predicate ?? inv.description))
    .filter((r): r is string => r !== null);

  const baseSchema = [
    `export const ${entity.name}Schema = z.object({`,
    ...zodFields,
    `})`,
  ].join("\n");

  const zodSchema =
    refines.length > 0
      ? baseSchema + "\n" + refines.join("\n") + ";"
      : baseSchema + ";";

  return [interfaceDeclaration, "", zodSchema].join("\n");
}

function emitBoundedContextUnion(
  ctx: BoundedContext,
  allEntities: readonly Entity[],
): string {
  const memberNames = ctx.entities.filter((name) =>
    allEntities.some((e) => e.name === name),
  );
  if (memberNames.length === 0) return "";
  const unionBody = memberNames.map((n) => `${n}Schema`).join(" | ");
  const safeCtxName = ctx.name.replace(/[^a-zA-Z0-9]/g, "_");
  return `export const ${safeCtxName}ContextSchema = z.union([${unionBody}] as const);`;
}

function buildSchemaFile(entityMap: EntityMap): string {
  const lines: string[] = [
    `// Auto-generated by Ada format stage`,
    `// Do not edit by hand — regenerate with ada compile`,
    `import { z } from "zod";`,
    ``,
  ];

  for (const entity of entityMap.entities) {
    lines.push(emitEntitySchema(entity));
    lines.push("");
  }

  for (const ctx of entityMap.boundedContexts) {
    const union = emitBoundedContextUnion(ctx, entityMap.entities);
    if (union) {
      lines.push(union);
      lines.push("");
    }
  }

  return lines.join("\n");
}

// ─── ER diagram emitter ──────────────────────────────────────────────────────

function inferRelationships(
  entities: readonly Entity[],
): Array<{ from: string; to: string; label: string }> {
  const entityNames = new Set(entities.map((e) => e.name.toLowerCase()));
  const rels: Array<{ from: string; to: string; label: string }> = [];

  for (const entity of entities) {
    for (const prop of entity.properties) {
      const typeKey = prop.type.toLowerCase().replace(/\[\]$/, "").trim();
      if (entityNames.has(typeKey) && typeKey !== entity.name.toLowerCase()) {
        const target = entities.find((e) => e.name.toLowerCase() === typeKey);
        if (target) {
          rels.push({ from: entity.name, to: target.name, label: prop.name });
        }
      }
    }
  }

  return rels;
}

function buildERDiagram(blueprint: Blueprint): string {
  const entities = blueprint.dataModel.entities;
  const lines: string[] = ["```mermaid", "erDiagram"];

  for (const entity of entities) {
    const id = mermaidId(entity.name);
    lines.push(`  ${id} {`);
    for (const prop of entity.properties) {
      const mType = prop.type.replace(/[^a-zA-Z0-9_[\]]/g, "_") || "string";
      lines.push(`    ${mType} ${mermaidId(prop.name)}`);
    }
    lines.push(`  }`);
  }

  const rels = inferRelationships(entities);
  for (const rel of rels) {
    lines.push(
      `  ${mermaidId(rel.from)} ||--o{ ${mermaidId(rel.to)} : "${rel.label}"`,
    );
  }

  for (const ctx of blueprint.dataModel.boundedContexts) {
    const root = mermaidId(ctx.rootEntity);
    for (const member of ctx.entities) {
      if (member !== ctx.rootEntity) {
        const memberId = mermaidId(member);
        const rootExists = entities.some((e) => e.name === ctx.rootEntity);
        const memberExists = entities.some((e) => e.name === member);
        if (rootExists && memberExists) {
          const already = rels.some(
            (r) => r.from === ctx.rootEntity && r.to === member,
          );
          if (!already) {
            lines.push(`  ${root} ||--o{ ${memberId} : "contains"`);
          }
        }
      }
    }
  }

  lines.push("```");
  return lines.join("\n");
}

function buildArchDiagram(blueprint: Blueprint): string {
  const components = blueprint.architecture.components;
  const lines: string[] = ["```mermaid", "graph TD"];

  for (const comp of components) {
    const id = mermaidId(comp.name);
    const label = comp.responsibility.replace(/"/g, "'").slice(0, 60);
    lines.push(`  ${id}["${comp.name}\\n${label}"]`);
  }

  for (const comp of components) {
    const fromId = mermaidId(comp.name);
    for (const dep of comp.dependencies) {
      const target = components.find(
        (c) => c.name === dep || c.name.toLowerCase() === dep.toLowerCase(),
      );
      if (target) {
        lines.push(`  ${fromId} --> ${mermaidId(target.name)}`);
      }
    }
  }

  const contextGroups = new Map<string, string[]>();
  for (const comp of components) {
    const ctx = comp.boundedContext || "Unassigned";
    const existing = contextGroups.get(ctx);
    if (existing) {
      existing.push(mermaidId(comp.name));
    } else {
      contextGroups.set(ctx, [mermaidId(comp.name)]);
    }
  }

  for (const [ctx, ids] of contextGroups) {
    lines.push(`  subgraph ${mermaidId(ctx)}["${ctx}"]`);
    for (const id of ids) lines.push(`    ${id}`);
    lines.push(`  end`);
  }

  lines.push("```");
  return lines.join("\n");
}

function buildDiagramFile(blueprint: Blueprint): string {
  const title = blueprint.summary.split(".")[0]?.trim() ?? "Project";
  const sections: string[] = [
    `# ${title} — Diagrams`,
    ``,
    `_Auto-generated by Ada format stage._`,
    ``,
    `## Entity Relationship`,
    ``,
    buildERDiagram(blueprint),
    ``,
  ];

  if (blueprint.architecture.components.length > 0) {
    sections.push(`## Architecture`);
    sections.push(``);
    sections.push(buildArchDiagram(blueprint));
    sections.push(``);
  }

  return sections.join("\n");
}

// ─── Placement map emitter ───────────────────────────────────────────────────

interface PlacementEntry {
  path: string;
  purpose: string;
  componentName: string;
  boundedContext: string;
  type: "source" | "test" | "config" | "doc";
}

function classifyEntryType(p: string): PlacementEntry["type"] {
  if (
    p.endsWith(".test.ts") ||
    p.endsWith(".spec.ts") ||
    p.endsWith(".test.js") ||
    p.endsWith(".spec.js")
  ) {
    return "test";
  }
  if (
    p.endsWith(".json") ||
    p.endsWith(".yaml") ||
    p.endsWith(".yml") ||
    p.endsWith(".toml")
  ) {
    return "config";
  }
  if (p.endsWith(".md") || p.endsWith(".txt")) return "doc";
  return "source";
}

function buildPlacementMap(blueprint: Blueprint): PlacementEntry[] {
  const entries: PlacementEntry[] = [
    {
      path: "package.json",
      purpose: "Package manifest — name, version, scripts, dependencies",
      componentName: "root",
      boundedContext: "root",
      type: "config",
    },
    {
      path: "tsconfig.json",
      purpose: "TypeScript compiler configuration",
      componentName: "root",
      boundedContext: "root",
      type: "config",
    },
    {
      path: "README.md",
      purpose: "Project overview and getting-started instructions",
      componentName: "root",
      boundedContext: "root",
      type: "doc",
    },
  ];

  if (blueprint.build && blueprint.build.fileTree.length > 0) {
    for (const node of blueprint.build.fileTree) {
      if (node.type !== "file") continue;
      entries.push({
        path: node.path,
        purpose: node.purpose,
        componentName: node.componentName ?? "unknown",
        boundedContext: node.boundedContext ?? "unknown",
        type: classifyEntryType(node.path.toLowerCase()),
      });
    }
  } else {
    for (const comp of blueprint.architecture.components) {
      const ctxDir = toPathSegment(comp.boundedContext);
      const compFile = toPathSegment(comp.name);
      entries.push({
        path: `src/${ctxDir}/${compFile}.ts`,
        purpose: comp.responsibility,
        componentName: comp.name,
        boundedContext: comp.boundedContext,
        type: "source",
      });
      entries.push({
        path: `src/${ctxDir}/${compFile}.test.ts`,
        purpose: `Unit tests for ${comp.name}`,
        componentName: comp.name,
        boundedContext: comp.boundedContext,
        type: "test",
      });
    }
  }

  return entries;
}

function buildPlacementFile(blueprint: Blueprint): string {
  const entries = buildPlacementMap(blueprint);
  const projectName =
    blueprint.summary.split(".")[0]?.trim() ?? "compiled-project";

  const lines: string[] = [
    `# ${projectName} — Placement Map`,
    ``,
    `_Auto-generated by Ada format stage. ${entries.length} entries._`,
    ``,
    `| Path | Purpose | Component | Context | Type |`,
    `|------|---------|-----------|---------|------|`,
  ];

  for (const e of entries) {
    lines.push(
      `| \`${e.path}\` | ${e.purpose} | ${e.componentName} | ${e.boundedContext} | ${e.type} |`,
    );
  }

  return lines.join("\n") + "\n";
}

// ─── Public API ──────────────────────────────────────────────────────────────

export interface FormatStageResult {
  readonly schemaFile: string;
  readonly diagramFile: string;
  readonly placementFile: string;
  readonly outputDir: string;
}

/**
 * Runs the format stage: emits schemas, diagrams, and a placement map.
 * Writes all artifacts to `<adaDir>/format/`.
 *
 * @param blueprint - A Blueprint (may be partial — missing fields produce
 *   minimal output rather than throwing).
 * @param adaDir - Absolute path to the `.ada` directory.
 */
export function runFormatStage(
  blueprint: Blueprint,
  adaDir: string,
): FormatStageResult {
  const formatDir = path.join(adaDir, "format");
  fs.mkdirSync(formatDir, { recursive: true });

  const schemaFile = path.join(formatDir, "schema.ts");
  const diagramFile = path.join(formatDir, "diagrams.md");
  const placementFile = path.join(formatDir, "placement.md");

  fs.writeFileSync(schemaFile, buildSchemaFile(blueprint.dataModel), "utf8");
  fs.writeFileSync(diagramFile, buildDiagramFile(blueprint), "utf8");
  fs.writeFileSync(placementFile, buildPlacementFile(blueprint), "utf8");

  return {
    schemaFile,
    diagramFile,
    placementFile,
    outputDir: formatDir,
  };
}
