// ─── G1: Gate Failure Payload ─────────────────────────────────────────────────

export interface GateFailurePayload {
  readonly gateId: string;
  readonly entropyValue: number;
  readonly failingInvariantRef: string;
  readonly compilationRunId: string;
}

// ─── G12: Threat Model Actor Classes ─────────────────────────────────────────

export type ActorClass =
  | "malicious-tool-input"
  | "misconfigured-agent"
  | "stale-blueprint";

// ─── G15: WHO Entity ──────────────────────────────────────────────────────────

export interface WHOEntity {
  readonly role: string;
  readonly scope: string;
  readonly trustLevel: "high" | "medium" | "low";
}

// ─── G11: Embedding (prompt-based semantic similarity) ────────────────────────
// Note: Anthropic has no text-embedding API. EmbeddingProvider uses structured
// LLM prompts to compute semantic similarity scores, not vector arithmetic.

export interface EmbeddingVector {
  readonly values: readonly number[];
  readonly dimensionality: number;
}

export interface EmbeddingProvider {
  embed(text: string): Promise<EmbeddingVector>;
}

// ─── G13: Drift Score ─────────────────────────────────────────────────────────

export interface DriftScore {
  readonly value: number; // 0–1, higher = more drift
  readonly threshold: number; // default 0.3 per G13
  readonly exceeded: boolean; // value > threshold
}

export interface DriftScoreCalculator {
  calculate(current: string, baseline: string): Promise<DriftScore>;
}

export type GovernorActivationEvent =
  | "pre-tool-use"
  | "token-checkpoint"
  | "explicit-drift";

// ─── G7 / G9: PreToolUse Hook ────────────────────────────────────────────────

export interface PreToolUseHook {
  readonly timeoutMs: 30000;
  readonly mode: "blocking" | "advisory";
  readonly triggeredBy: string;
}

// ─── G4 / G9: Bootstrap Seed ─────────────────────────────────────────────────
// Static artifact checked into source control. Never generated by the pipeline.

export interface MetaInvariantEntry {
  readonly id: string;
  readonly text: string;
  readonly rule: string;
}

export interface BootstrapSeed {
  readonly version: string;
  readonly immutable: true;
  readonly metaInvariants: readonly MetaInvariantEntry[];
}
