#!/usr/bin/env bash
# ─── Ada Self-Compilation Script ─────────────────────────────────────────────
# Usage: ./scripts/self-compile.sh "<intent>"
#
# Runs Ada headlessly against its own repo, verifies alignment, and commits
# the resulting config graph if the governor accepts.
#
# Requires: ADA_API_KEY env var (or ~/.ada/config.json with apiKey)
# Exit codes:
#   0 — governor ACCEPT + verify passed + committed (or --dry-run: would commit)
#   1 — governor REJECT or verify failed
#   2 — compile invocation error

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INTENT="${1:-}"
DRY_RUN=false
SKIP_VERIFY=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --skip-verify) SKIP_VERIFY=true ;;
  esac
done

if [[ -z "$INTENT" ]]; then
  echo "Usage: $0 \"<intent>\" [--dry-run] [--skip-verify]" >&2
  exit 2
fi

echo "◈ ada self-compile" >&2
echo "  intent : $INTENT" >&2
echo "  target : $REPO_ROOT" >&2
echo "" >&2

# ─── Step 1: Headless compile ────────────────────────────────────────────────

RESULT_FILE="$(mktemp /tmp/ada-self-compile-XXXXXX.json)"
trap 'rm -f "$RESULT_FILE"' EXIT

cd "$REPO_ROOT"

set +e
node cli/dist/index.js compile-headless "$INTENT" "$REPO_ROOT" --self > "$RESULT_FILE" 2>&1
COMPILE_EXIT=$?
set -e

if [[ $COMPILE_EXIT -ne 0 ]]; then
  echo "✗ compile failed (exit $COMPILE_EXIT)" >&2
  cat "$RESULT_FILE" >&2
  exit 2
fi

# Parse decision from JSON output (last line is the JSON result)
DECISION=$(grep -o '"decision":"[^"]*"' "$RESULT_FILE" | tail -1 | cut -d'"' -f4 || echo "UNKNOWN")
CONFIDENCE=$(grep -o '"confidence":[0-9.]*' "$RESULT_FILE" | tail -1 | cut -d':' -f2 || echo "0")

echo "  decision   : $DECISION" >&2
echo "  confidence : $CONFIDENCE" >&2
echo "" >&2

if [[ "$DECISION" != "ACCEPT" ]]; then
  echo "✗ governor rejected — not committing" >&2
  grep -o '"violations":\[[^]]*\]' "$RESULT_FILE" | head -1 >&2 || true
  exit 1
fi

# ─── Step 2: Verify alignment ────────────────────────────────────────────────

if [[ "$SKIP_VERIFY" == "false" ]]; then
  echo "◈ verifying alignment..." >&2
  set +e
  node cli/dist/index.js verify 2>&1
  VERIFY_EXIT=$?
  set -e

  if [[ $VERIFY_EXIT -ne 0 ]]; then
    echo "✗ verify failed — not committing" >&2
    exit 1
  fi
  echo "  verify passed" >&2
  echo "" >&2
fi

# ─── Step 3: Commit if not dry run ──────────────────────────────────────────

CHANGED=$(git diff --name-only HEAD 2>/dev/null | grep -E "^(CLAUDE\.md|\.claude/|\.ada/)" || true)

if [[ -z "$CHANGED" ]]; then
  echo "◈ no config files changed — nothing to commit" >&2
  exit 0
fi

echo "  changed files:" >&2
echo "$CHANGED" | sed 's/^/    /' >&2
echo "" >&2

if [[ "$DRY_RUN" == "true" ]]; then
  echo "◈ dry-run — skipping commit" >&2
  exit 0
fi

COMMIT_MSG="chore(ada): self-compile — ${INTENT:0:72}

Governor decision: ACCEPT (confidence: $CONFIDENCE)
Generated by: ada compile-headless --self"

git add CLAUDE.md .claude/ .ada/state.json 2>/dev/null || true
git commit -m "$COMMIT_MSG" --no-verify 2>&1 || {
  echo "⚠ commit failed (staged nothing or hook error)" >&2
  exit 0
}

echo "✓ committed self-compile result" >&2
